[workspace]
name = "yohane"
channels = ["conda-forge"]
platforms = ["linux-64", "osx-arm64", "win-64"]

[dependencies]
python = "~=3.15.0a3"
ffmpeg = ">=4.4,<7"

[pypi-dependencies]
yohane = { path = ".", editable = true }
yohane-cli = { path = "yohane-cli", editable = true }
vocal-remover = { git = "https://github.com/Japan7/vocal-remover.git", branch = "6.0.0b4" }
